#!/bin/bash

#global constants
ledoff=0
ledblink=1
ledsolid=2

count=0

err=1

while [[ 1 -lt 2 ]]
do
  read pid <~/ledpid
  fun=$(ps -p $pid)
  if ! [[ "$fun" =~ "$pid" ]]
  then
    python ~/asynchleds.py & sleep 3
  fi

  err=0

  #step 1: check if ethernet is physically conected
  connected=$(cat /sys/class/net/eth0/carrier)
  if [[ $connected -eq 0 ]]
  then
    ~/adafruitdisplay.py "ethernet{disconnected!"
    python ~/ledhandler.py $ledblink
    err=1
  fi

  #step 2: check if state of ethernet connection is "up"
  link_status=$(cat /sys/class/net/eth0/operstate)
  if [[ $link_status != "up" ]] && [[ $err -ne 1 ]]
  then
    ~/adafruitdisplay.py "connection{not up!"
    python ~/ledhandler.py $ledblink
    err=1
  fi

  #step 3: check if ping is successful
  ping -c 1 64.233.178.105 &>/dev/null
  if [[ $? -ne 0 ]] && [[ $err -ne 1 ]]
  then
    ~/adafruitdisplay.py "internet{unreachable!"
    python ~/ledhandler.py $ledblink
    err=1
  fi

  #step 4: check if at least one peer is on the network
  peers=$(owlcoind getpeerinfo)
  if [[ $peers = "[]" ]] && [[ $err -ne 1 ]]
  then
    ~/adafruitdisplay.py "no peers{on network!"
    python ~/ledhandler.py $ledblink
    err=1
  fi

  #step 5: run owlcoind to check balances
  /usr/local/bin/owlcoind getbalance >~/balance.txt 2>~/error.txt
  /usr/local/bin/owlcoind setgenerate true -1 2>>~/error.txt
  if [[ -s ~/error.txt ]] && [[ $err -ne 1 ]]   #checks if there are any contents in the file
  then
    read msg <~/error.txt
    if [[ "$msg" = "error: couldn't connect to server" ]]
    #most likely due to the server not being running, assuming
    #ethernet checks do what they are intended to
    then
      /usr/local/bin/owlcoind
      ~/adafruitdisplay.py "starting up..." $count
      printf "" >~/coindata.dat
      python ~/ledhandler.py $ledsolid
      err=1
    elif [[ "$msg" =~ "owlcoind is probably already running" ]]
    #this occurs while owlcoind is still starting up.
    #no worries!
    then
      ~/adafruitdisplay.py "starting up..." $count
      python ~/ledhandler.py $ledsolid
      err=1
    else
      #unknown error generated by owlcoind.
      #best we can do is try to display it
      ~/adafruitdisplay.py <~/error.txt
      python ~/ledhandler.py $ledblink
      err=1
    fi
  elif [[ $err -ne 1 ]]
  then
    #everything's good? time to write
    read bal <~/balance.txt
    ~/adafruitdisplay.py $bal $count dab
    python ~/ledhandler.py $ledoff
  fi

  sleep 1
  count=$((count+1))
done
